import type { Proc } from '../../algorithms/types';

export const TT_INIT = '2_3_Init';
export const TT_SEARCH = '2_3_Search';
export const TT_MINIMUM = '2_3_Minimum';
export const TT_SUCCESSOR = '2_3_Successor';
export const UPDATE_KEY = 'Update_Key';
export const SET_CHILDREN = 'Set_Children';
export const INSERT_AND_SPLIT = 'Insert_And_Split';
export const TT_INSERT = '2_3_Insert';
export const BORROW_OR_MERGE = 'Borrow_Or_Merge';
export const TT_DELETE = '2_3_Delete';

// Efficient DS slides 21–38 (2-3 trees; objects live at the leaves, key = maximum key in the subtree).
export const twoThreeProcs: Proc[] = [
  {
    name: TT_SEARCH,
    signature: '2_3_Search(x, k)',
    lines: [
      'if x is a leaf then',
      '    if x.key == k then',
      '        return x',
      '    else return NIL',
      'if k ≤ x.left.key then',
      '    return 2_3_Search(x.left, k)',
      'else if k ≤ x.middle.key then',
      '    return 2_3_Search(x.middle, k)',
      'else return 2_3_Search(x.right, k)',
    ],
  },
  {
    name: TT_MINIMUM,
    signature: '2_3_Minimum(T)',
    lines: [
      'x = T.root',
      'while x is not a leaf do',
      '    x = x.left',
      'x = x.p.middle',
      'if x.key ≠ +∞ then',
      '    return x',
      'else error: T is empty',
    ],
  },
  {
    name: TT_SUCCESSOR,
    signature: '2_3_Successor(x)',
    lines: [
      'z = x.p',
      'while x == z.right or (z.right == NIL and x == z.middle) do',
      '    x = z',
      '    z = z.p',
      'if x == z.left then',
      '    y = z.middle',
      'else y = z.right',
      'while y is not a leaf do',
      '    y = y.left',
      'if y.key < +∞ then',
      '    return y',
      'else return NIL',
    ],
  },
  {
    name: TT_INSERT,
    signature: '2_3_Insert(T, z)',
    lines: [
      'y = T.root',
      'while y is not a leaf do',
      '    if z.key < y.left.key then y = y.left',
      '    else if z.key < y.middle.key then y = y.middle',
      '    else y = y.right',
      'x = y.p',
      'z = Insert_And_Split(x, z)',
      'while x ≠ T.root do',
      '    x = x.p',
      '    if z ≠ NIL then',
      '        z = Insert_And_Split(x, z)',
      '    else Update_Key(x)',
      'if z ≠ NIL then',
      '    new internal node w',
      '    Set_Children(w, x, z, NIL)',
      '    T.root = w',
    ],
  },
  {
    name: INSERT_AND_SPLIT,
    signature: 'Insert_And_Split(x, z)',
    lines: [
      '⟨ℓ, m, r⟩ = ⟨x.left, x.middle, x.right⟩',
      'if r == NIL then',
      '    if z.key < ℓ.key then',
      '        Set_Children(x, z, ℓ, m)',
      '    else if z.key < m.key then',
      '        Set_Children(x, ℓ, z, m)',
      '    else Set_Children(x, ℓ, m, z)',
      '    return NIL',
      'new internal node y',
      'if z.key < ℓ.key then',
      '    Set_Children(x, z, ℓ, NIL)',
      '    Set_Children(y, m, r, NIL)',
      'else if z.key < m.key then',
      '    Set_Children(x, ℓ, z, NIL)',
      '    Set_Children(y, m, r, NIL)',
      'else if z.key < r.key then',
      '    Set_Children(x, ℓ, m, NIL)',
      '    Set_Children(y, z, r, NIL)',
      'else Set_Children(x, ℓ, m, NIL)',
      '    Set_Children(y, r, z, NIL)',
      'return y',
    ],
  },
  {
    name: SET_CHILDREN,
    signature: 'Set_Children(x, ℓ, m, r)',
    lines: [
      '⟨x.left, x.middle, x.right⟩ = ⟨ℓ, m, r⟩',
      'ℓ.p = x',
      'if m ≠ NIL then',
      '    m.p = x',
      'if r ≠ NIL then',
      '    r.p = x',
      'Update_Key(x)',
    ],
  },
  {
    name: UPDATE_KEY,
    signature: 'Update_Key(x)',
    lines: [
      'x.key = x.left.key',
      'if x.middle ≠ NIL then',
      '    x.key = x.middle.key',
      'if x.right ≠ NIL then',
      '    x.key = x.right.key',
    ],
  },
  {
    name: TT_DELETE,
    signature: '2_3_Delete(T, x)',
    lines: [
      'y = x.p',
      'if x == y.left then',
      '    Set_Children(y, y.middle, y.right, NIL)',
      'else if x == y.middle then',
      '    Set_Children(y, y.left, y.right, NIL)',
      'else Set_Children(y, y.left, y.middle, NIL)',
      'delete x    ▷ deg(y) may be < 2',
      'while y ≠ NIL do',
      '    if y.middle ≠ NIL then',
      '        Update_Key(y)',
      '        y = y.p',
      '    else',
      '        if y ≠ T.root then',
      '            y = Borrow_Or_Merge(y)',
      '        else T.root = y.left',
      '            y.left.p = NIL',
      '            delete y',
      '            return',
    ],
  },
  {
    name: BORROW_OR_MERGE,
    signature: 'Borrow_Or_Merge(y)',
    lines: [
      'z = y.p',
      'if y == z.left then',
      '    x = z.middle',
      '    if x.right ≠ NIL then',
      '        Set_Children(y, y.left, x.left, NIL)',
      '        Set_Children(x, x.middle, x.right, NIL)',
      '    else Set_Children(x, y.left, x.left, x.middle)',
      '        delete y',
      '        Set_Children(z, x, z.right, NIL)',
      '    return z',
      'if y == z.middle then',
      '    x = z.left',
      '    if x.right ≠ NIL then',
      '        Set_Children(y, x.right, y.left, NIL)',
      '        Set_Children(x, x.left, x.middle, NIL)',
      '    else Set_Children(x, x.left, x.middle, y.left)',
      '        delete y',
      '        Set_Children(z, x, z.right, NIL)',
      '    return z',
      '▷ y == z.right',
      'x = z.middle',
      'if x.right ≠ NIL then',
      '    Set_Children(y, x.right, y.left, NIL)',
      '    Set_Children(x, x.left, x.middle, NIL)',
      'else Set_Children(x, x.left, x.middle, y.left)',
      '    delete y',
      '    Set_Children(z, z.left, x, NIL)',
      'return z',
    ],
  },
  {
    name: TT_INIT,
    signature: '2_3_Init(T)',
    lines: [
      'new internal node x    ▷ DS attributes initialized to NIL',
      'new leaves ℓ, m    ▷ DS attributes initialized to NIL',
      'ℓ.key = −∞',
      'm.key = +∞',
      'ℓ.p = m.p = x',
      'x.key = +∞',
      'x.left = ℓ',
      'x.middle = m',
      'T.root = x',
    ],
  },
];
